---
- hosts: localhost
  vars:
    credentials:
      controller: 10.10.29.90
      username: admin
      password: "{{avi_password}}"
      api_version: 17.2.7
  roles:
    - role: avinetworks.avisdk
  tasks:
    - avi_sslkeyandcertificate:
        avi_credentials: "{{ credentials }}"
        key_params:
          ec_params:
            curve: SSL_KEY_EC_CURVE_SECP256R1
          rsa_params:
            key_size: SSL_KEY_2048_BITS
            exponent: 65537
          algorithm: SSL_KEY_ALGORITHM_RSA
        status: SSL_CERTIFICATE_FINISHED
        type: SSL_CERTIFICATE_TYPE_VIRTUALSERVICE
        certificate:
          days_until_expire: 365
          expiry_status: SSL_CERTIFICATE_GOOD
          self_signed: true
          subject:
            common_name: avi.avinetworks.com
        certificate_base64: true
        key_base64: true
        name: new_cert2
