---
- hosts: localhost
  connection: local
  vars:
    avi_credentials:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      api_version: "{{ api_version }}"
  roles:
      - role: avinetworks.avisdk
  tasks:
    - name: Upload package on controller
      avi_api_fileservice:
          avi_credentials: "{{ avi_credentials }}"
          upload: true
          timeout: 300
          path: /upload/
          file_path: /path/to/the/controller_pkg
    - name: Upgrade controller
      avi_api_session:
          avi_credentials: "{{ avi_credentials }}"
          http_method: post
          timeout: 300
          path: cluster/upgrade/
          data:
            image_path: controller://upgrade_pkgs/controller.pkg
            force: true
            disruptive: true
          

